/* Optional integration QA against a disposable headless Chrome on localhost:9229. */
const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{const tabs=await (await fetch('http://127.0.0.1:9229/json')).json();const tab=tabs.find(t=>t.type==='page');const ws=new WebSocket(tab.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map(),errors=[];ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}if(m.method==='Page.javascriptDialogOpening')send('Page.handleJavaScriptDialog',{accept:true});if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text+': '+m.params.exceptionDetails.exception?.description);};const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};const sleep=ms=>new Promise(r=>setTimeout(r,ms));const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);const fill=(selector,value)=>evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.focus();el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));})()`);const text=()=>evaluate('document.body.innerText');
await send('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});await send('Runtime.enable');await send('Page.enable');await send('Network.enable');await send('Network.setCacheDisabled',{cacheDisabled:true});await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://127.0.0.1:8000'});await sleep(1200);await (async()=>{const d=await send('DOM.getDocument');const n=await send('DOM.querySelector',{nodeId:d.root.nodeId,selector:'#project-file'});await send('DOM.setFileInputFiles',{nodeId:n.nodeId,files:[process.cwd()+'/examples/demo.phonegame']});await sleep(400);})();assert.match(await text(),/Всё начинается с дизайна/);fs.mkdirSync('.tmp',{recursive:true});let shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('.tmp/editor-desktop.png',Buffer.from(shot.data,'base64'));
await click('[data-state="task"]');await click('[data-section="tasks"]');await fill('[data-path="task.question"]','Проверка живого предпросмотра');assert.match(await evaluate('document.querySelector("#game").innerText'),/Проверка живого предпросмотра/);await click('#undo');assert.match(await evaluate('document.querySelector("#game").innerText'),/Какое время года/);await click('#redo');assert.match(await evaluate('document.querySelector("#game").innerText'),/Проверка живого/);await click('#undo');
// Keep the exact input node, cursor and draft while changing appearance.
await evaluate('document.querySelectorAll("[data-pick-task]")[2].click()');await click('[data-show="task"]');await fill('[data-answer]','Привет');await evaluate('window.qaAnswer=document.querySelector("[data-answer]");qaAnswer.setSelectionRange(2,2)');await click('[data-section="design"]');await fill('[data-path="design.accent"]','#5555cc');assert.equal(await evaluate('document.querySelector("[data-answer]")===window.qaAnswer'),true);assert.equal(await evaluate('document.querySelector("[data-answer]").value'),'Привет');
await click('[data-section="language"]');await fill('[data-path="language.locale"]','tr');await click('[data-state="keyboard"]');await click('[data-value="ı"]');assert.match(await evaluate('document.querySelector("[data-answer]").value'),/ı/);await fill('[data-path="language.locale"]','kk');await click('[data-value="ә"]');assert.match(await evaluate('document.querySelector("[data-answer]").value'),/ә/);
// Responsive layout has no page-level horizontal overflow.
for(const width of [320,375,768,1024,1440]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<700});await sleep(60);assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,`width ${width}`);if(width<700){await click('[data-mobile="preview"]');assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);if(width===375){shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('.tmp/editor-mobile.png',Buffer.from(shot.data,'base64'));}}}
await send('Emulation.setDeviceMetricsOverride',{width:1100,height:1000,deviceScaleFactor:1,mobile:false});await click('#genially');await fill('#embed-url','file:///tmp/game.html');assert.equal(await evaluate('document.querySelector("#copy-embed").disabled'),true);await fill('#embed-url','https://example.com/game.html');assert.match(await evaluate('document.querySelector("#embed-code").value'),/^<iframe src="https:/);await click('#dialog-close');
// Import through the actual file picker handler; bad inputs must preserve the project.
const setFile=async path=>{const doc=await send('DOM.getDocument');const found=await send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'#project-file'});await send('DOM.setFileInputFiles',{nodeId:found.nodeId,files:[path]});await sleep(700);};
await setFile(process.cwd()+'/examples/demo.phonegame');assert.match(await text(),/Проект загружен/);assert.equal(await evaluate('document.querySelector("#project-name").value'),'Телефон знаний');
fs.writeFileSync('.tmp/broken.phonegame','not a zip');await setFile(process.cwd()+'/.tmp/broken.phonegame');assert.match(await text(),/Повреждённый ZIP/);assert.equal(await evaluate('document.querySelector("#project-name").value'),'Телефон знаний');
fs.writeFileSync('.tmp/large.phonegame','');fs.truncateSync('.tmp/large.phonegame',101*1024*1024);await setFile(process.cwd()+'/.tmp/large.phonegame');assert.match(await text(),/превышает 100 МБ/);fs.unlinkSync('.tmp/large.phonegame');
// Export / ZIP validation in a real browser engine.
const archive=await evaluate(`(async()=>{const p=PhoneModel.demo();const b=PhoneArchive.save(p);const q=await PhoneArchive.load(await b.arrayBuffer());return JSON.stringify(p)===JSON.stringify(q);})()`);assert.equal(archive,true);
await send('Page.navigate',{url:'http://127.0.0.1:8000/examples/game.html'});await sleep(500);await click('[data-action="play"]');await click('.pg-center [data-action="contacts"]');await evaluate('document.querySelectorAll("[data-action=call]")[0].click()');await click('[data-action="skip"]');await evaluate(`Array.from(document.querySelectorAll('.pg-options [data-action=choice]')).find(x=>x.textContent.includes('Лето')).click()`);await click('[data-action="submit"]');assert.match(await text(),/Верно: 1 из 6/);await click('[data-action="next"]');await evaluate(`Array.from(document.querySelectorAll('.pg-options [data-action=choice]')).filter(x=>['А','О'].includes(x.querySelector('span:last-child').textContent)).forEach(x=>x.click())`);await click('[data-action="submit"]');await click('[data-action="next"]');await fill('[data-answer]','5');await click('[data-action="submit"]');await click('[data-action="next"]');await evaluate('document.querySelectorAll("[data-action=call]")[1].click()');await click('[data-action="skip"]');await evaluate(`(()=>{let rows=[...document.querySelectorAll('[data-order]')];for(let i=0;i<rows.length;i++){let target=rows.find(r=>r.querySelector('span').textContent.endsWith(['2','5','9'][i]));while([...document.querySelectorAll('[data-order]')].indexOf(target)>i)target.querySelector('[data-action=up]').click();}})()`);await click('[data-action="submit"]');await click('[data-action="next"]');assert.equal(await evaluate('!!document.querySelector("audio")'),true);await fill('[data-answer]','wrong');await click('[data-action="submit"]');await click('[data-action="next"]');await fill('[data-answer]','wrong');await click('[data-action="submit"]');assert.match(await text(),/Игра завершена/);assert.match(await text(),/4 \/ 6/);shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('.tmp/game-result.png',Buffer.from(shot.data,'base64'));
// file:// autonomous export in offline mode.
await send('Network.enable');await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await send('Page.navigate',{url:'file://'+process.cwd()+'/examples/game.light.html'});await sleep(600);assert.match(await text(),/Алло, знания!/);await click('[data-action="play"]');await click('.pg-center [data-action="contacts"]');assert.match(await text(),/Лиса Алиса/);assert.equal(await evaluate('document.fonts.check("16px Nunito")'),true);await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});assert.deepEqual(errors,[]);console.log('PASS: editor, undo/redo, live input preservation, TR/KZ keyboard, 5 widths, iframe validation, ZIP round trip, 5 task formats, 4/6 result, offline file://, no JS errors');ws.close();})().catch(e=>{console.error(e);process.exit(1);});
