#!/usr/bin/env python3
"""Rebuild export source bundle using only the Python standard library."""
import base64, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sources = {name: (ROOT / 'src' / filename).read_text() for name, filename in [('model','model.js'),('i18n','i18n.js'),('game','game.js'),('css','game.css'),('math','math.js')]}
sources['katex'] = (ROOT/'vendor/katex/katex.min.js').read_text()
sources['fonts'] = {label: base64.b64encode((ROOT/'assets/fonts'/filename).read_bytes()).decode() for label,filename in [('Nunito','Nunito.ttf'),('Roboto','Roboto.ttf'),('Open Sans','OpenSans.ttf'),('Noto Sans','NotoSans.ttf')]}
sources['licenses'] = '\n\n'.join(p.read_text() for p in sorted((ROOT/'assets/fonts').glob('*-OFL.txt')))
sources['licenses'] += '\n\nKaTeX\n' + (ROOT/'vendor/katex/LICENSE').read_text()
(ROOT/'src/export-sources.js').write_text('/* Generated by scripts/build.py. Do not edit. */\nglobalThis.PhoneExportSources='+json.dumps(sources,ensure_ascii=False,separators=(',',':'))+';\n')
print('Built src/export-sources.js')
