const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const tabs=await(await fetch('http://127.0.0.1:9229/json')).json(),ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map(),errors=[];ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}if(m.method==='Page.javascriptDialogOpening')send('Page.handleJavaScriptDialog',{accept:true});if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description);};const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});const run=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description);return r.result.value;};const wait=ms=>new Promise(r=>setTimeout(r,ms));const until=async expr=>{for(let i=0;i<80;i++){if(await run(expr))return;await wait(150);}throw Error('Timeout: '+expr);};const click=s=>run(`document.querySelector(${JSON.stringify(s)}).click()`);const fill=(s,v)=>run(`(()=>{const e=document.querySelector(${JSON.stringify(s)});e.focus();e.value=${JSON.stringify(v)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);const file=async(s,path)=>{const d=await send('DOM.getDocument');const node=await send('DOM.querySelector',{nodeId:d.root.nodeId,selector:s});await send('DOM.setFileInputFiles',{nodeId:node.nodeId,files:[process.cwd()+'/'+path]});await wait(250);};
await send('Runtime.enable');await send('Network.enable');await send('Network.setCacheDisabled',{cacheDisabled:true});await send('Page.enable');await send('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://127.0.0.1:8000'});await wait(800);
fs.mkdirSync('.tmp/fixtures',{recursive:true});const png=await run(`(()=>{const c=document.createElement('canvas');c.width=1500;c.height=1000;const ctx=c.getContext('2d'),g=ctx.createLinearGradient(0,0,1500,1000);g.addColorStop(0,'#583585');g.addColorStop(1,'#e5c4ee');ctx.fillStyle=g;ctx.fillRect(0,0,1500,1000);return c.toDataURL('image/png');})()`);fs.writeFileSync('.tmp/fixtures/background.png',Buffer.from(png.split(',')[1],'base64'));
await file('#project-file','examples/demo.phonegame');await until('document.querySelector("#toast").textContent==="Проект загружен"');
assert.equal(await run('document.querySelector("#help")'),null);assert.match(await run('document.body.innerText'),/Все права защищены и принадлежат Гальмиз Марии Александровне/);
await click('[data-section="language"]');await fill('[data-path="language.locale"]','tr');await click('[data-state="task"]');assert.match(await run('document.querySelector("#game").innerText'),/Yanıtla/);await click('[data-state="keyboard"]');assert.match(await run('document.querySelector(".pg-keyboard").innerText'),/A/);
await click('[data-section="tasks"]');await run('document.querySelectorAll("[data-pick-task]")[2].click()');await click('[data-state="keyboard"]');assert.equal(await run('document.querySelector("[data-value=ı]")?.textContent'),'ı');await click('[data-value="ı"]');await click('[data-action="layout"][data-layout="math"]');await click('[data-value="√"]');assert.equal(await run('document.querySelector("[data-answer]").value'),'ı√');await click('[data-action="layout"][data-layout="tr"]');assert.equal(await run('document.querySelector("[data-answer]").value'),'ı√');
await fill('[data-path="task.question"]',String.raw`Вычисли $\frac{3}{4}+\sqrt{9}$ и $$\begin{cases}x+y=5\\x-y=1\end{cases}$$`);assert.ok(await run('document.querySelectorAll("#game math").length>=2'));assert.ok(await run('!!document.querySelector("#game mfrac")'));
await click('[data-section="heroes"]');await click('[data-upload="hero.avatar"]');await file('#media-file','tests/fixtures/animated.gif');await until('!document.querySelector("#dialog").open');await until('!!document.querySelector(".avatar-preview img")');assert.match(await run('document.querySelector(".avatar-preview img").src'),/^data:image\/gif/);
const gifData=await run('document.querySelector(".avatar-preview img").src');fs.writeFileSync('.tmp/compressed.gif',Buffer.from(gifData.split(',')[1],'base64'));assert.ok(fs.statSync('.tmp/compressed.gif').size<fs.statSync('tests/fixtures/animated.gif').size);
await click('[data-section="screens"]');for(const k of ['win','lose']){await click(`[data-upload="screens.${k}Image"]`);await file('#media-file','tests/fixtures/animated.gif');await until('!document.querySelector("#dialog").open');await click(`[data-show="${k}"]`);assert.match(await run('document.querySelector(".pg-result-image").src'),/^data:image\/gif/);}
await click('[data-section="design"]');await click('[data-upload="design.screenBackground"]');await file('#media-file','.tmp/fixtures/background.png');await until('!document.querySelector("#dialog").open');assert.match(await run('document.querySelector("#game").style.getPropertyValue("--screen-image")'),/data:image\/webp/);
// Code needs no manually hosted game URL, and optimization targets the copied iframe.
await click('#genially');await until('!document.querySelector("#copy-embed").disabled');const normal=await run('document.querySelector("#embed-code").value');assert.match(normal,/player\.html#pg2j\./);await click('#lighten-embed');await until('!document.querySelector("#copy-embed").disabled');const compact=await run('document.querySelector("#embed-code").value');assert.match(compact,/player\.html#pg2z\./);assert.ok(compact.length<normal.length);await click('#copy-embed');await wait(100);assert.match(await run('document.querySelector("#embed-note").textContent'),/Код скопирован/);
await click('#test-embed');await until('!!document.querySelector("#embed-test iframe")?.contentDocument?.querySelector(".pg-phone")');assert.match(await run('document.querySelector("#embed-test iframe").contentDocument.body.innerText'),/Oyna/);const payload=await run('new URL(document.querySelector("#embed-test iframe").src).hash');const decoded=await run(`PhoneEmbed.decode(${JSON.stringify(payload)}).then(p=>({language:p.language.locale,avatar:p.assets[p.heroes[0].avatar].type,win:p.assets[p.screens.winImage].type,bg:p.assets[p.design.screenBackground].type,math:p.heroes[0].tasks[2].question}))`);assert.equal(decoded.language,'tr');assert.equal(decoded.avatar,'image/gif');assert.equal(decoded.win,'image/gif');assert.equal(decoded.bg,'image/webp');assert.match(decoded.math,/\\frac/);
const shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('.tmp/genially-upgrade.png',Buffer.from(shot.data,'base64'));await click('#dialog-close');
// All requested LaTeX examples remain native MathML in the standalone export.
const math=await run(`(()=>{const html=PhoneMath.render(String.raw\`$\\frac{a}{b}$ $x^{10}$ $a_{n+1}$ $\\sqrt[n]{a}$ $\\left|x\\right|$ $\\sum_{i=1}^{n}i$ $\\lim_{x\\to 0}f(x)$ $\\angle ABC$ $90^\\circ$ $\\triangle ABC$ $a\\parallel b$ $a\\perp b$ $\\overline{AB}$ $S=24\\text{ см}^2$\`);return {count:(html.match(/<math/g)||[]).length,errors:html.includes('pg-math-error')};})()`);assert.equal(math.count,14);assert.equal(math.errors,false);
const exported=await run(`PhoneEmbed.decode(${JSON.stringify(payload)}).then(p=>PhoneArchive.html(p,PhoneExportSources,true))`);fs.writeFileSync('.tmp/current-game.html',exported);
await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await send('Page.navigate',{url:'file://'+process.cwd()+'/.tmp/current-game.html'});await wait(700);assert.match(await run('document.body.innerText'),/Oyna/);await run('window.offlineGame=new PhoneGame.Game(document.querySelector("#game"),project);offlineGame.show("task",project.heroes[0].id,project.heroes[0].tasks[2].id)');
assert.ok(await run('!!document.querySelector("mfrac")'));await run('offlineGame.show("win")');assert.match(await run('document.querySelector(".pg-result-image").src'),/^data:image\/gif/);await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
console.log('PASS upgrade: auto-compressed animated GIF, result pictures, phone background, 1 language, letter/math keyboard, LaTeX, gzip iframe round trip, copy and embedded player',{normal:normal.length,compact:compact.length,saved:Math.round((1-compact.length/normal.length)*100)+'%',gifBefore:fs.statSync('tests/fixtures/animated.gif').size,gifAfter:fs.statSync('.tmp/compressed.gif').size});assert.deepEqual(errors,[]);ws.close();})().catch(e=>{console.error(e);process.exit(1)});
