(function(root){'use strict';
const enc=new TextEncoder(),dec=new TextDecoder();
const table=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc(bytes){let n=0xffffffff;for(const b of bytes)n=table[(n^b)&255]^(n>>>8);return (n^0xffffffff)>>>0;}
function zip(files){let offset=0;const chunks=[],central=[];for(const [name,data] of Object.entries(files)){const n=enc.encode(name),bytes=typeof data==='string'?enc.encode(data):data,c=crc(bytes),header=new Uint8Array(30+n.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,c,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,n.length,true);header.set(n,30);chunks.push(header,bytes);const cd=new Uint8Array(46+n.length),cv=new DataView(cd.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,c,true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);cv.setUint16(28,n.length,true);cv.setUint32(42,offset,true);cd.set(n,46);central.push(cd);offset+=header.length+bytes.length;}const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,central.reduce((n,b)=>n+b.length,0),true);v.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'});}
async function unzip(buffer){if(buffer.byteLength>100*1024*1024)throw Error('Проект превышает 100 МБ.');const bytes=new Uint8Array(buffer),v=new DataView(buffer),files={};let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(v.getUint32(i,true)===0x06054b50){end=i;break;}if(end<0)throw Error('Повреждённый ZIP проекта.');if(v.getUint16(end+4,true)||v.getUint16(end+6,true))throw Error('Многотомные ZIP не поддерживаются.');const count=v.getUint16(end+10,true);if(count>5000)throw Error('Слишком много ресурсов в проекте.');let pos=v.getUint32(end+16,true),total=0;for(let i=0;i<count;i++){if(pos+46>end||v.getUint32(pos,true)!==0x02014b50)throw Error('Повреждённый каталог ZIP.');const flags=v.getUint16(pos+8,true),method=v.getUint16(pos+10,true),expected=v.getUint32(pos+16,true),size=v.getUint32(pos+20,true),rawSize=v.getUint32(pos+24,true),nl=v.getUint16(pos+28,true),extra=v.getUint16(pos+30,true),comment=v.getUint16(pos+32,true),local=v.getUint32(pos+42,true);total+=rawSize;if(total>100*1024*1024||flags&1||![0,8].includes(method))throw Error('Неподдерживаемый или слишком большой ZIP.');const name=dec.decode(bytes.slice(pos+46,pos+46+nl));if(name.includes('..')||name.startsWith('/')||Object.hasOwn(files,name)||!/^manifest\.json$|^assets\/[\w.-]+$/.test(name))throw Error('Недопустимый путь в ZIP.');if(local+30>bytes.length||v.getUint32(local,true)!==0x04034b50)throw Error('Повреждённый ресурс ZIP.');const start=local+30+v.getUint16(local+26,true)+v.getUint16(local+28,true);if(start+size>bytes.length)throw Error('Ресурс обрезан.');let out=bytes.slice(start,start+size);if(method===8){try{const stream=new Blob([out]).stream().pipeThrough(new DecompressionStream('deflate-raw')),reader=stream.getReader(),parts=[];let n=0;while(true){const {done,value}=await reader.read();if(done)break;n+=value.length;if(n>rawSize||n>100*1024*1024){await reader.cancel();throw Error('Лимит распаковки');}parts.push(value);}out=new Uint8Array(await new Blob(parts).arrayBuffer());}catch{throw Error('Не удалось распаковать ресурс ZIP.');}}if(out.length!==rawSize||crc(out)!==expected)throw Error('Нарушена целостность ресурса ZIP.');files[name]=out;pos+=46+nl+extra+comment;}return files;}
function fromData(data){const raw=atob(data.split(',')[1]);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function toData(bytes,type){let chunks=[];for(let i=0;i<bytes.length;i+=32768)chunks.push(String.fromCharCode(...bytes.subarray(i,i+32768)));return 'data:'+type+';base64,'+btoa(chunks.join(''));}
function save(p){const manifest=PhoneModel.clone(p),files={};for(const [id,a] of Object.entries(manifest.assets)){const path='assets/'+id;files[path]=fromData(a.data);delete a.data;a.path=path;}files['manifest.json']=JSON.stringify(manifest,null,2);return zip(files);}
async function load(buffer){const files=await unzip(buffer);if(!files['manifest.json'])throw Error('В ZIP отсутствует manifest.json.');let p;try{p=JSON.parse(dec.decode(files['manifest.json']));}catch{throw Error('Повреждён manifest.json.');}if(![1,2].includes(p.schemaVersion))throw Error('Версия проекта не поддерживается. Ожидается schemaVersion: 1 или 2.');if(!p.assets||typeof p.assets!=='object'||Array.isArray(p.assets))throw Error('Отсутствует каталог ресурсов.');for(const [id,a] of Object.entries(p.assets)){if(!a||a.path!=='assets/'+id||!files[a.path])throw Error('В архиве отсутствует ресурс '+id);a.data=toData(files[a.path],a.type);delete a.path;}return PhoneModel.assertSchema(p);}
function html(project,sources,compact=false){const p=PhoneModel.exportCopy(project),font=p.design.font;let css=sources.css.replace(/@font-face\{[^}]+\}/g,'');const embedded=[...new Set([font,'Noto Sans'])].filter(f=>sources.fonts[f]);css=embedded.map(f=>`@font-face{font-family:'${f}';src:url(data:font/ttf;base64,${sources.fonts[f]})}`).join('')+css;let js=(sources.katex||'')+'\n'+sources.model+'\n'+sources.i18n+'\n'+(sources.math||'')+'\n'+sources.game;if(compact){css=css.replace(/\s*([{}:;,])\s*/g,'$1').trim();js=js.replace(/\n[ \t]+(?=function |const |class |if\()/g,'\n');}const data=JSON.stringify(p).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');return `<!doctype html>\n<!-- Bundled font licenses\n${(sources.licenses||'').replace(/-->/g,'-- >')}\n-->\n<html lang="${p.language.locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${p.name.replace(/[&<>"']/g,c=>'&#'+c.charCodeAt(0)+';')}</title><style>html,body{margin:0;min-height:100%;}body{min-height:100vh;display:flex;}#game{min-height:100vh;}${css}</style></head><body><main id="game"></main><script>${js.replace(/<\/script/gi,'<\\/script')}\nconst project=${data};new PhoneGame.Game(document.getElementById('game'),project);<\/script></body></html>`;}
root.PhoneArchive={crc,zip,unzip,save,load,html,fromData,toData};
})(globalThis);
