(function(){'use strict';
const M=PhoneModel,E=PhoneGame.esc,$=s=>document.querySelector(s),clone=M.clone;
let project=M.demo(),heroId=project.heroes[0].id,taskId=project.heroes[0].tasks[0].id,section='design',savedSignature='',db=null,saveTimer,typing=null,mediaTarget=null,testMode=false,drag=null,working=null;
const signature=p=>JSON.stringify({...p,assets:Object.fromEntries(Object.entries(p.assets).map(([k,a])=>[k,{name:a.name,type:a.type,length:a.data.length}]))});
const past=[],future=[];const game=new PhoneGame.Game($('#game'),project);
const sections=[['design','◈','Дизайн'],['heroes','♙','Герои'],['tasks','☷','Задания'],['game','♡','Игра'],['language','⌨','Язык'],['screens','▣','Экраны'],['sounds','♫','Звуки']];
const states=[['start','Старт'],['phone','Телефон'],['contacts','Контакты'],['calling','Звонок'],['task','Задание'],['keyboard','Клавиатура'],['win','Победа'],['complete','Итог'],['lose','Поражение']];
const types={single:'Один ответ',multi:'Множественный выбор',text:'Ввод ответа',order:'По порядку',audio:'Аудио'};
const hero=()=>project.heroes.find(h=>h.id===heroId),task=()=>hero()?.tasks.find(t=>t.id===taskId);
const opt=(options,value)=>Object.entries(options).map(([v,t])=>`<option value="${E(v)}" ${String(value)===v?'selected':''}>${E(t)}</option>`).join('');
function field(label,path,value,type='text',attrs=''){return `<label class="field"><span>${E(label)}</span><input type="${type}" data-path="${path}" value="${E(value)}" ${attrs}></label>`;}
function area(label,path,value,hint=''){return `<label class="field"><span>${E(label)}</span><textarea data-path="${path}">${E(value)}</textarea>${hint?`<small>${E(hint)}</small>`:''}</label>`;}
function select(label,path,value,options){return `<label class="field"><span>${E(label)}</span><select data-path="${path}">${opt(options,value)}</select></label>`;}
function check(label,path,value){return `<label class="field check"><input type="checkbox" data-path="${path}" ${value?'checked':''}><span>${E(label)}</span></label>`;}
function range(label,path,value,min,max,step=1){return `<label class="field"><span>${E(label)} <output>${value}</output></span><input type="range" data-path="${path}" value="${value}" min="${min}" max="${max}" step="${step}"></label>`;}
function upload(label,path,value,kind){return `<label class="field"><span>${E(label)}</span><button class="upload-box" data-upload="${path}" data-kind="${kind}">${value?'✓ '+E(project.assets[value]?.name||'Ресурс'):'＋ Загрузить '+(kind==='audio'?'MP3 / WAV':'картинку или GIF')}</button>${value?`<button class="text-btn danger" data-remove-media="${path}">Удалить файл</button>`:''}</label>`;}
function heading(title,subtitle){return `<h2>${title}</h2><p class="subtitle">${subtitle}</p>`;}
function pathParts(path){if(path.startsWith('hero.'))return [hero(),path.slice(5).split('.')];if(path.startsWith('task.'))return [task(),path.slice(5).split('.')];return [project,path.split('.')];}
function setPath(path,value){const [base,parts]=pathParts(path);if(!base)return;let node=base;for(const key of parts.slice(0,-1))node=node[key];node[parts.at(-1)]=value;}
function remember(){past.push(clone(project));if(past.length>120)past.shift();future.length=0;}
function beginGroup(key){if(typing!==key){remember();typing=key;}}
function finishGroup(){typing=null;}
function mutate(fn,rerender=true){finishGroup();remember();fn();changed(rerender);}
function changed(rerender=false){$('#draft-state').textContent='Сохраняем черновик…';game.update(project);fitPreview();if(rerender)render();else status();clearTimeout(saveTimer);saveTimer=setTimeout(saveDraft,650);}
function status(){$('#undo').disabled=!past.length;$('#redo').disabled=!future.length;$('#dirty-state').textContent=savedSignature===signature(project)?'Файл сохранён':'Есть изменения';$('#project-count').textContent=`${project.heroes.length} героев · ${M.active(project).length} заданий`;$('#preview-size').textContent=`${project.design.width} × ${Math.round(project.design.width*1.83)} px`;if(document.activeElement!==$('#project-name'))$('#project-name').value=project.name;}
function undo(redo=false){finishGroup();const from=redo?future:past,to=redo?past:future;if(!from.length)return;to.push(clone(project));project=from.pop();ensureSelection();changed(true);toast(redo?'Действие повторено':'Действие отменено');}
function ensureSelection(){if(!hero())heroId=project.heroes[0]?.id;if(!task())taskId=hero()?.tasks[0]?.id;}
function toast(message){const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4500);}
function render(){ensureSelection();$('#sections').innerHTML=sections.map(([id,icon,label])=>`<button data-section="${id}" class="${section===id?'active':''}">${icon} ${label}</button>`).join('');$('#states').innerHTML=states.map(([id,label])=>`<button data-state="${id}" ${testMode?'disabled':''} class="${game.view===id?'active':''}">${label}</button>`).join('');$('#settings').innerHTML=renderSection();status();}
function renderSection(){const d=project.design,g=project.game,l=project.language,h=hero(),t=task();switch(section){case 'design':return heading('Всё начинается с дизайна','Выберите телефон и создайте настроение вашей игры.')+`<div class="section-label">Шаблон телефона</div><div class="templates">${[['modern','Смартфон'],['retro','Ретро'],['school','Учебный']].map(([id,name])=>`<button class="template ${d.template===id?'active':''}" data-template="${id}"><span class="mini-phone ${id}">✦</span>${name}</button>`).join('')}</div><div class="section-label">Размер телефона</div><div class="presets">${[[300,'Маленький'],[360,'Средний'],[440,'Большой']].map(([n,label])=>`<button data-width="${n}">${label}</button>`).join('')}</div>`+range('Ширина, px','design.width',d.width,280,600)+`<div class="divider"></div><div class="section-label">Палитра</div><div class="color-grid">${[['scene','Фон сцены'],['body','Корпус телефона'],['screen','Экран'],['accent','Кнопки'],['hover','Кнопки при наведении'],['text','Текст']].map(([k,label])=>`<label class="field"><span>${label}</span><span class="color-control"><input type="color" data-path="design.${k}" value="${d[k]}"><code>${d[k].toUpperCase()}</code></span></label>`).join('')}</div>`+upload('Изображение фона','design.background',d.background,'background')+(d.background?select('Размещение фона','design.fit',d.fit,{cover:'Заполнить',contain:'Вписать'})+range('Прозрачность фона','design.backgroundOpacity',d.backgroundOpacity,0,1,.05):'')+upload('Фон экрана телефона','design.screenBackground',d.screenBackground,'background')+(d.screenBackground?select('Фон внутри телефона','design.screenFit',d.screenFit,{cover:'Заполнить',contain:'Вписать'}):'')+`<div class="divider"></div>`+select('Шрифт игры','design.font',d.font,Object.fromEntries(M.fonts.map(f=>[f,f])))+`<div class="font-sample" style="font-family:'${d.font}',Arial,'Noto Sans'">Алло, знания! Aa Әә İı</div>`+range('Заголовок игры, px','design.titleSize',d.titleSize,20,48)+range('Описание игры, px','design.introSize',d.introSize,12,28)+range('Вопрос, px','design.questionSize',d.questionSize,14,32)+range('Ответы, px','design.answerSize',d.answerSize,14,26)+range('Имена, px','design.nameSize',d.nameSize,12,24)+range('Кнопки, px','design.buttonSize',d.buttonSize,12,24)+range('Аватар на титульном экране, px','design.startAvatarSize',d.startAvatarSize,60,220)+check('Отобразить аватары горизонтально','design.horizontalAvatars',d.horizontalAvatars)+range('Прозрачность сцены','design.sceneOpacity',d.sceneOpacity,0,1,.05);
case 'heroes':return heading('Кто на связи?','Добавляйте героев и приглашайте учеников к разговору.')+project.heroes.map((x,i)=>`<div class="hero-card ${x.id===heroId?'active':''}" draggable="true" data-drag-hero="${x.id}"><div class="card-title" data-pick-hero="${x.id}" tabindex="0" role="button"><span class="card-avatar">${x.avatar?`<img src="${E(project.assets[x.avatar]?.data)}" alt="">`:E(x.name.slice(0,2))}</span><span>${E(x.name)}<small>${x.tasks.filter(t=>t.enabled).length} заданий · ${x.enabled?'В игре':'Выключен'}</small></span><span>⠿</span></div><div class="card-actions"><button data-hero-action="up" data-id="${x.id}" aria-label="Герой выше" ${i===0?'disabled':''}>↑</button><button data-hero-action="down" data-id="${x.id}" aria-label="Герой ниже" ${i===project.heroes.length-1?'disabled':''}>↓</button><button data-hero-action="copy" data-id="${x.id}" title="Дублировать героя">⧉</button><button data-hero-action="remove" data-id="${x.id}" class="danger" title="Удалить героя">×</button></div></div>`).join('')+`<button class="add-button" data-add-hero>＋ Добавить героя</button>`+(h?`<div class="divider"></div>`+field('Имя героя','hero.name',h.name)+check('Герой участвует в игре','hero.enabled',h.enabled)+(!h.tasks.some(t=>t.enabled)?'<div class="warning">У героя пока нет активных заданий. В контактах он отображается сразу, но звонок станет доступен после добавления задания.</div>':'')+area('Приветствие','hero.greeting',h.greeting)+upload('Аватар','hero.avatar',h.avatar,'avatar')+(h.avatar?`<div class="avatar-preview" style="border-radius:${h.shape==='circle'?'50%':'15px'}"><img src="${E(project.assets[h.avatar].data)}" alt="Аватар героя" style="object-position:${h.x}% ${h.y}%"></div>`:'')+range('Размер аватара в контактах, px','hero.avatarSize',h.avatarSize,36,100)+select('Эффект при наведении','hero.hoverEffect',h.hoverEffect,{none:'Без эффекта',grow:'Увеличение',bounce:'Подпрыгивание',wiggle:'Покачивание',rotate:'Поворот',pulse:'Пульсация'})+select('Форма аватара','hero.shape',h.shape,{circle:'Круг',square:'Скруглённый квадрат'})+`<button class="wide" data-show="contacts">Показать в телефоне ↗</button><button class="add-button" data-goto-tasks>Перейти к заданиям →</button>`:'');
case 'tasks':return heading('О чём поговорим?','Пять форматов заданий для маленьких открытий.')+(project.heroes.length?`<label class="field"><span>Герой</span><select id="task-hero">${opt(Object.fromEntries(project.heroes.map(h=>[h.id,h.name])),heroId)}</select></label>`+h.tasks.map((x,i)=>`<div class="task-card ${x.id===taskId?'active':''}" draggable="true" data-drag-task="${x.id}"><div class="card-title" role="button" tabindex="0" data-pick-task="${x.id}"><span>${String(i+1).padStart(2,'0')}</span><span>${E(x.question.slice(0,70))}<small>${types[x.type]}${x.enabled?'':' · Выключено'}</small></span></div><div class="card-actions"><button data-task-action="up" data-id="${x.id}" aria-label="Задание выше" ${i===0?'disabled':''}>↑</button><button data-task-action="down" data-id="${x.id}" aria-label="Задание ниже" ${i===h.tasks.length-1?'disabled':''}>↓</button><button data-task-action="copy" data-id="${x.id}" aria-label="Дублировать задание">⧉</button><button data-task-action="remove" data-id="${x.id}" aria-label="Удалить задание" class="danger">×</button></div></div>`).join('')+`<button class="add-button" data-add-task>＋ Добавить задание</button>`+(t?`<div class="divider"></div>`+select('Тип задания','task.type',t.type,types)+check('Задание активно','task.enabled',t.enabled)+area('Вопрос','task.question',t.question)+formulaTools()+upload('Изображение к вопросу','task.image',t.image,'image')+(t.type==='audio'?upload('Аудиозапись','task.audio',t.audio,'audio')+select('Как отвечает ученик','task.audioMode',t.audioMode,{single:'Один вариант',multi:'Несколько вариантов',text:'Текст'}):'')+renderAnswerEditor(t)+area('Пояснение после ответа','task.explanation',t.explanation)+`<button class="wide primary" data-show="task">Показать задание ↗</button>`:''):`<div class="warning">Сначала добавьте героя.</div><button data-section="heroes" class="primary">Добавить героя</button>`);
case 'game':return heading('Правила вашей игры','Настройте жизни, ошибки и темп разговора.')+check('Неограниченные жизни','game.unlimited',g.unlimited)+(!g.unlimited?field('Количество жизней','game.lives',g.lives,'number','min="1" max="20" step="1"'):'')+select('Значок жизни','game.lifeIcon',g.lifeIcon,{'❤️':'❤️ Сердце','⭐':'⭐ Звезда','🍎':'🍎 Яблоко','🌸':'🌸 Цветок','⚡':'⚡ Молния','💎':'💎 Алмаз','😊':'😊 Смайлик',...(!['❤️','⭐','🍎','🌸','⚡','💎','😊'].includes(g.lifeIcon)?{[g.lifeIcon]:g.lifeIcon+' Свой значок'}:{})})+field('Свой эмодзи','game.lifeIcon',g.lifeIcon,'text','data-emoji maxlength="40"')+select('Показывать жизни','game.lifeDisplay',g.lifeDisplay,{row:'Ряд значков',count:'Значок и число'})+`<p class="hint">При количестве больше 10 автоматически показывается число.</p><div class="divider"></div>`+check('Повторять до правильного ответа','game.retry',g.retry)+`<p class="hint">${g.retry?'Ошибка расходует жизнь. Новая попытка доступна после изменения ответа.':'Ошибка расходует жизнь и завершает задание. Ученик переходит к следующему.'}</p>`+range('Длительность звонка, сек.','game.callSeconds',g.callSeconds,0,5,.5)+`<div class="warning">За правильный ответ — 1 балл. Всего в игре ${M.active(project).length} активных заданий.</div>`;
case 'language':return heading('Один язык для всей игры','Служебные надписи, проверка текста и буквенная клавиатура используют выбранный язык.')+select('Язык игры','language.locale',l.locale,M.locales)+`<div class="language-preview"><strong>${E(PhoneI18n.t(project,'play'))} · ${E(PhoneI18n.t(project,'contacts'))}</strong><p>${E(PhoneI18n.t(project,'submit'))} · ${E(PhoneI18n.t(project,'clear'))} · ${E(PhoneI18n.t(project,'next'))}</p></div><p class="hint">Вопросы, имена и ваши собственные тексты сохраняются. В телефоне доступны буквенная раскладка, цифры и математические символы.</p>`;
case 'screens':return heading('Первое и последнее слово','Встречайте учеников и поддерживайте их на финише.')+field('Заголовок стартового экрана','screens.title',project.screens.title)+area('Описание игры','screens.intro',project.screens.intro)+upload('Аватар на титульный экран','screens.startAvatar',project.screens.startAvatar,'avatar')+upload('GIF на титульный экран','screens.startGif',project.screens.startGif,'result')+`<button class="wide" data-show="start">Показать старт ↗</button><div class="divider"></div>`+field('Название второго экрана','screens.phoneTitle',project.screens.phoneTitle)+upload('Аватар на второй экран','screens.phoneAvatar',project.screens.phoneAvatar,'avatar')+upload('GIF на второй экран','screens.phoneGif',project.screens.phoneGif,'result')+`<button class="wide" data-show="phone">Показать второй экран ↗</button><div class="divider"></div>`+[['win','Победа без ошибок'],['complete','Игра завершена с ошибками'],['lose','Жизни закончились']].map(([k,title])=>area(title,'screens.'+k,project.screens[k],'Оставьте пустым для стандартного перевода.')+upload('Картинка или GIF результата','screens.'+k+'Image',project.screens[k+'Image'],'result')+field('Фон результата','screens.'+k+'Color',project.screens[k+'Color'],'color')+`<button class="wide" data-show="${k}">Показать результат ↗</button>`).join('');
case 'sounds':return heading('Звучит как игра','Звуки включаются после первого действия ученика.')+range('Общая громкость','sounds.volume',project.sounds.volume,0,1,.05)+['ring','correct','wrong'].map((k,i)=>`<div class="divider"></div>`+check(['Звук звонка','Правильный ответ','Неправильный ответ'][i],'sounds.'+k,project.sounds[k])+upload('Свой звук (необязательно)','sounds.'+k+'Asset',project.sounds[k+'Asset'],'audio')+`<button class="wide" data-play-sound="${k}">▷ Прослушать</button>`).join('')+`<p class="hint">Без загруженного файла используется встроенный сигнал. Ученик может выключить звук в телефоне.</p>`;}}
let formulaTarget='task.question';
const formulaTemplates=[['Дробь',String.raw`$\frac{a}{b}$`],['Степень','$x^2$'],['Индекс','$a_{n+1}$'],['Корень',String.raw`$\sqrt{x}$`],['Система',String.raw`$$\begin{cases}x+y=5\\x-y=1\end{cases}$$`],['Сумма',String.raw`$\sum_{i=1}^{n} i$`],['Предел',String.raw`$\lim_{x\to 0}f(x)$`],['Угол',String.raw`$\angle ABC$`],['Знаки',String.raw`$\pm\;\neq\;\leq\;\geq\;\pi\;\infty$`],['Единицы',String.raw`$S=24\text{ см}^2$`]];
function formulaTools(){return `<details class="formula-tools"><summary>∑ Вставить формулу LaTeX</summary><p class="hint">Пишите $...$ внутри строки или $$...$$ для отдельной формулы. Шаблон вставляется в последнее выбранное поле вопроса или варианта ответа.</p><div class="formula-buttons">${formulaTemplates.map(([label],i)=>`<button type="button" data-formula="${i}">${label}</button>`).join('')}</div></details>`;}
$('#settings').addEventListener('focusin',e=>{if(e.target.dataset.path==='task.question'||e.target.dataset.path==='task.explanation')formulaTarget=e.target.dataset.path;else if(e.target.dataset.optionText!==undefined)formulaTarget='option:'+e.target.dataset.optionText;});
$('#settings').addEventListener('click',e=>{const b=e.target.closest('[data-formula]');if(!b)return;const value=formulaTemplates[+b.dataset.formula][1],selector=formulaTarget.startsWith('option:')?`[data-option-text="${formulaTarget.slice(7)}"]`:`[data-path="${formulaTarget}"]`,input=$(selector)||$('[data-path="task.question"]');if(!input)return;const start=input.selectionStart??input.value.length,end=input.selectionEnd??start;input.value=input.value.slice(0,start)+value+input.value.slice(end);input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();input.setSelectionRange(start+value.length,start+value.length);});
function renderAnswerEditor(t){const m=M.mode(t);if(m==='text')return area('Допустимые ответы','task.answers',t.answers.join('\n'),'Каждый допустимый ответ — с новой строки.')+check('Учитывать регистр','task.caseSensitive',t.caseSensitive)+check('Игнорировать пунктуацию','task.ignorePunctuation',t.ignorePunctuation)+check('Считать ё и е одинаковыми','task.yoEqualsE',t.yoEqualsE);return `<div class="section-label">${m==='order'?'Эталонный порядок':'Варианты ответа'}</div><p class="hint">${m==='order'?'Укажите правильную последовательность. В игре она будет перемешана.':'Отметьте '+(m==='single'?'один правильный вариант.':'все правильные варианты.')}</p>${t.options.map((o,i)=>`<div class="option-edit">${m==='order'?`<button data-option-move="${i}" aria-label="Элемент выше" ${i===0?'disabled':''}>↑</button>`:`<input type="${m==='single'?'radio':'checkbox'}" name="correct" data-correct="${o.id}" aria-label="Правильный вариант ${i+1}" ${t.correct.includes(o.id)?'checked':''}>`}<input aria-label="Вариант ${i+1}" type="text" data-option-text="${i}" value="${E(o.text)}"><button data-option-remove="${i}" aria-label="Удалить вариант ${i+1}" ${t.options.length<=2?'disabled':''}>×</button></div>`).join('')}<button class="add-button" data-option-add ${t.options.length>=(m==='order'?10:8)?'disabled':''}>＋ Добавить ${m==='order'?'элемент':'вариант'}</button>`+(m!=='order'?check('Перемешивать варианты','task.shuffle',t.shuffle):'');}
function handleInput(e){const el=e.target,path=el.dataset.path;if(el.dataset.optionText!==undefined){beginGroup('option-'+el.dataset.optionText);task().options[+el.dataset.optionText].text=el.value;changed();return;}if(!path)return;if(el.type==='checkbox'||el.tagName==='SELECT')return;let value=el.type==='range'||el.type==='number'?Number(el.value):el.value;if(el.type==='number'&&(el.value===''||value<+el.min||value>+el.max||!Number.isInteger(value)))return;if(el.hasAttribute('data-emoji')){const parts=[...new Intl.Segmenter('ru',{granularity:'grapheme'}).segment(value)];if(parts.length!==1||!/[\p{Extended_Pictographic}\p{Regional_Indicator}\u20e3]/u.test(value))return;}if(path==='task.answers')value=value.split('\n');beginGroup(path);setPath(path,value);if(el.type==='range')el.previousElementSibling.querySelector('output').textContent=value;if(el.type==='color'){const code=el.parentElement.querySelector('code');if(code)code.textContent=value.toUpperCase();}changed();}
$('#settings').addEventListener('input',handleInput);
$('#settings').addEventListener('focusout',e=>{finishGroup();if((e.target.type==='number'||e.target.hasAttribute('data-emoji'))&&e.target.dataset.path){const [base,parts]=pathParts(e.target.dataset.path);e.target.value=parts.reduce((o,k)=>o[k],base);}});
$('#settings').addEventListener('change',e=>{const el=e.target,path=el.dataset.path;if(el.id==='task-hero'){heroId=el.value;taskId=hero()?.tasks[0]?.id;render();return;}if(el.dataset.layoutToggle){mutate(()=>{const value=el.dataset.layoutToggle,l=project.language;if(el.checked)l.layouts.push(value);else if(l.layouts.length>1)l.layouts=l.layouts.filter(x=>x!==value);else toast('Оставьте хотя бы одну раскладку');if(!l.layouts.includes(l.initial))l.initial=l.layouts[0];});return;}if(el.dataset.correct){mutate(()=>{const t=task(),id=el.dataset.correct;if(M.mode(t)==='single')t.correct=[id];else t.correct=el.checked?[...new Set([...t.correct,id])]:t.correct.filter(x=>x!==id);});return;}if(path&&(el.type==='checkbox'||el.tagName==='SELECT')){mutate(()=>{setPath(path,el.type==='checkbox'?el.checked:el.value);if(path==='language.locale'){M.setLanguage(project,el.value);project.language.overrides={};}if(path==='task.type'||path==='task.audioMode'){const t=task();if(M.mode(t)==='single')t.correct=[t.options[0].id];if(M.mode(t)!=='order'&&t.options.length>8){t.options=t.options.slice(0,8);t.correct=t.correct.filter(id=>t.options.some(o=>o.id===id));}}});}else finishGroup();});
function duplicateTask(t){const n=clone(t);n.id=M.uid();const ids={};n.options.forEach(o=>{const old=o.id;o.id=M.uid();ids[old]=o.id;});n.correct=n.correct.map(x=>ids[x]);return n;}
function reorder(list,id,delta){const i=list.findIndex(x=>x.id===id),j=i+delta;if(i>=0&&j>=0&&j<list.length)[list[i],list[j]]=[list[j],list[i]];}
async function confirmDelete(kind,id){const name=kind==='hero'?project.heroes.find(x=>x.id===id)?.name:hero()?.tasks.find(x=>x.id===id)?.question;modal('Удалить '+(kind==='hero'?'героя?':'задание?'),`<p>${E(name)}</p><p>Действие можно будет отменить кнопкой «Обратно».</p><div class="row"><button id="cancel-delete">Отмена</button><button id="confirm-delete" class="danger">Удалить</button></div>`);$('#cancel-delete').onclick=closeModal;$('#confirm-delete').onclick=()=>{mutate(()=>{if(kind==='hero')project.heroes=project.heroes.filter(h=>h.id!==id);else hero().tasks=hero().tasks.filter(t=>t.id!==id);});closeModal();};}
document.addEventListener('click',e=>{const el=e.target.closest('button,[data-pick-hero],[data-pick-task]');if(!el)return;const a=el.dataset;if(a.section){section=a.section;finishGroup();render();}if(a.template)mutate(()=>project.design.template=a.template);if(a.width)mutate(()=>project.design.width=+a.width);if(a.pickHero){heroId=a.pickHero;taskId=hero()?.tasks[0]?.id;render();}if(a.pickTask){taskId=a.pickTask;render();game.show('task',heroId,taskId);}if('addHero'in a)mutate(()=>{const h=M.hero('Герой '+(project.heroes.length+1));project.heroes.push(h);heroId=h.id;});if('addTask'in a)mutate(()=>{const t=M.task();t.locale=project.language.locale;hero().tasks.push(t);taskId=t.id;});if(a.heroAction){if(a.heroAction==='remove')confirmDelete('hero',a.id);else mutate(()=>{if(a.heroAction==='copy'){const n=clone(project.heroes.find(h=>h.id===a.id));n.id=M.uid();n.name+=' — копия';n.tasks=n.tasks.map(duplicateTask);project.heroes.push(n);heroId=n.id;}else reorder(project.heroes,a.id,a.heroAction==='up'?-1:1);});}if(a.taskAction){if(a.taskAction==='remove')confirmDelete('task',a.id);else mutate(()=>{if(a.taskAction==='copy'){const n=duplicateTask(hero().tasks.find(t=>t.id===a.id));hero().tasks.push(n);taskId=n.id;}else reorder(hero().tasks,a.id,a.taskAction==='up'?-1:1);});}if('gotoTasks'in a){section='tasks';render();}if('optionAdd'in a)mutate(()=>task().options.push({id:M.uid(),text:'Новый вариант'}));if('optionRemove'in a)mutate(()=>{const removed=task().options.splice(+a.optionRemove,1)[0];task().correct=task().correct.filter(id=>id!==removed.id);});if('optionMove'in a)mutate(()=>{const i=+a.optionMove,o=task().options;[o[i-1],o[i]]=[o[i],o[i-1]];});if(a.show||a.state){testMode=false;setMode(false);game.show(a.show||a.state,heroId,taskId);$('#states').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.state===(a.show||a.state)));if(innerWidth<=700)setMobile('preview');}if(a.upload){mediaTarget={path:a.upload,kind:a.kind,heroId,taskId};$('#media-file').accept=a.kind==='audio'?'.mp3,.wav':'image/png,image/jpeg,image/webp,image/gif';$('#media-file').click();}if(a.removeMedia)mutate(()=>setPath(a.removeMedia,null));if(a.playSound)game.play(a.playSound);if('resetLabels'in a)mutate(()=>project.language.overrides={});if(a.mobile)setMobile(a.mobile);});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);}if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-pick-hero],[data-pick-task]')){e.preventDefault();e.target.click();}});
$('#settings').addEventListener('dragstart',e=>{const el=e.target.closest('[data-drag-hero],[data-drag-task]');if(el&&!e.target.matches('input,textarea')){drag={kind:el.dataset.dragHero?'hero':'task',id:el.dataset.dragHero||el.dataset.dragTask};e.dataTransfer.setData('text/plain',drag.id);}});
$('#settings').addEventListener('dragover',e=>{if(e.target.closest('[data-drag-hero],[data-drag-task]'))e.preventDefault();});
$('#settings').addEventListener('drop',e=>{const el=e.target.closest('[data-drag-hero],[data-drag-task]');if(!el||!drag)return;e.preventDefault();const target=drag.kind==='hero'?el.dataset.dragHero:el.dataset.dragTask;if(target)mutate(()=>{const arr=drag.kind==='hero'?project.heroes:hero().tasks,i=arr.findIndex(x=>x.id===drag.id),j=arr.findIndex(x=>x.id===target);if(i>=0&&j>=0)arr.splice(j,0,arr.splice(i,1)[0]);});drag=null;});
$('#project-name').oninput=e=>{beginGroup('name');project.name=e.target.value;changed();};$('#project-name').onblur=finishGroup;
$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);
function setMode(test){testMode=test;$('#test-mode').classList.toggle('active',test);$('#edit-mode').classList.toggle('active',!test);$('#states').querySelectorAll('button').forEach(b=>b.disabled=test);if(test)game.reset(project);}
$('#test-mode').onclick=()=>{const errors=M.validate(project);if(errors.length){showErrors(errors);return;}setMode(true);};$('#edit-mode').onclick=()=>setMode(false);$('#restart').onclick=()=>game.reset(project);$('#zoom').onchange=e=>$('#game').dataset.fit=e.target.value;
function fitPreview(){const box=$('#viewport'),host=$('#game'),width=project.design.width;const scale=$('#zoom').value==='actual'?1:Math.min(1,Math.max(.2,(host.clientWidth-32)/width),Math.max(.2,(box.clientHeight-36)/(width*1.83)));host.style.setProperty('--preview-scale',scale);}
new ResizeObserver(fitPreview).observe($('#viewport'));
$('#zoom').addEventListener('change',fitPreview);
$('#device').onchange=e=>{const width=e.target.value;$('#game').style.width=width==='auto'?'100%':width+'px';$('#viewport').style.justifyContent=width==='auto'?'center':'flex-start';fitPreview();};
function setMobile(which){document.body.dataset.mobile=which;document.querySelectorAll('[data-mobile]').forEach(el=>el.classList.toggle('active',el.dataset.mobile===which));}
function modal(title,html){$('#dialog-body').onclick=null;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();}
function closeModal(){if(working){working.cancel();working=null;}$('#dialog').close();}
$('#dialog-close').onclick=closeModal;$('#dialog').addEventListener('cancel',()=>{if(working){working.cancel();working=null;}});
function showErrors(errors){modal('Проверьте игру',`<p>Исправьте ошибки перед экспортом. Незавершённый проект можно сохранить.</p><div class="errors">${errors.map((err,i)=>`<button data-error="${i}">${i+1}. ${E(err.message)}</button>`).join('')}</div>`);$('#dialog-body').onclick=e=>{const b=e.target.closest('[data-error]');if(!b)return;const err=errors[+b.dataset.error];if(err.heroId)heroId=err.heroId;if(err.taskId)taskId=err.taskId;section=err.taskId?'tasks':'heroes';closeModal();render();setMobile('settings');};}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function filename(ext){return (project.name.replace(/[\\/:*?"<>|]/g,'-').trim()||'phonegame')+ext;}
async function operation(kind,p,extra={}){modal('Подготовка файла','<p>Обрабатываем проект и ресурсы…</p><div class="progress"><span></span></div><button id="cancel-work" class="wide">Отменить</button>');return new Promise((resolve,reject)=>{let worker;const cancel=()=>{worker?.terminate();reject(Error('Операция отменена'));};working={cancel};$('#cancel-work').onclick=closeModal;const finish=(err,result)=>{worker?.terminate();working=null;if(err)reject(Error(err));else resolve(result);};try{worker=new Worker('src/worker.js');worker.onmessage=e=>finish(e.data.error,e.data.result);worker.onerror=()=>{worker.terminate();fallback();};worker.postMessage({kind,project:p,...extra});}catch{fallback();}async function fallback(){try{await new Promise(r=>setTimeout(r,0));let out;if(kind==='save')out=PhoneArchive.save(p);if(kind==='load')out=await PhoneArchive.load(extra.buffer);if(kind==='html')out=new Blob([PhoneArchive.html(p,PhoneExportSources,extra.compact)],{type:'text/html;charset=utf-8'});finish(null,out);}catch(e){finish(e.message);}}});}
async function saveProject(){try{finishGroup();const copy=clone(project),sig=signature(copy),blob=await operation('save',copy);if(blob.size>100*1024*1024)throw Error('Проект больше 100 МБ. Удалите лишние ресурсы.');download(blob,filename('.phonegame'));savedSignature=sig;$('#download-state').textContent='Скачивание проекта запущено · '+new Date().toLocaleTimeString('ru',{hour:'2-digit',minute:'2-digit'});closeModal();status();toast('Файл .phonegame передан браузеру для скачивания');return true;}catch(e){closeModal();toast(e.message);return false;}}
$('#save').onclick=saveProject;
$('#load').onclick=()=>{if(savedSignature!==signature(project)){modal('Загрузить другой проект?',`<p>В текущем проекте есть изменения. Сохраните файл перед заменой, если хотите вернуться к нему.</p><div class="row"><button id="cancel-load">Отмена</button><button id="continue-load">Продолжить загрузку</button><button id="save-load" class="primary">Сохранить и загрузить</button></div>`);$('#cancel-load').onclick=closeModal;$('#continue-load').onclick=()=>{closeModal();$('#project-file').click();};$('#save-load').onclick=async()=>{if(await saveProject())$('#project-file').click();};}else $('#project-file').click();};
$('#project-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(!file.name.toLowerCase().endsWith('.phonegame'))throw Error('Выберите файл .phonegame.');if(file.size>100*1024*1024)throw Error('Файл проекта превышает 100 МБ.');let p=await operation('load',null,{buffer:await file.arrayBuffer()});let cancelled=false;working={cancel:()=>cancelled=true};await verifyAssets(p,()=>cancelled);if(cancelled)throw Error('Операция отменена');working=null;p=await optimizeLoaded(p);project=p;past.length=0;future.length=0;finishGroup();savedSignature=signature(p);heroId=p.heroes[0]?.id;taskId=hero()?.tasks[0]?.id;game.reset(p);render();saveDraft();closeModal();toast('Проект загружен');}catch(e){closeModal();toast(e.message);}};
async function exportHtml(compact=false,p=project){const errors=M.validate(p);if(errors.length){showErrors(errors);return;}try{const blob=await operation('html',clone(p),{sources:PhoneExportSources,compact});download(blob,filename(compact?'.light.html':'.html'));closeModal();toast('Автономная игра готова к скачиванию');}catch(e){closeModal();toast(e.message);}}
$('#export').onclick=()=>exportHtml();
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open('phonegame-editor',1);req.onupgradeneeded=()=>req.result.createObjectStore('drafts');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function saveDraft(){if(!db)return;try{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put({project,savedSignature,at:Date.now()},'latest');await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});$('#draft-state').textContent='✓ Черновик сохранён в этом браузере';}catch{$('#draft-state').textContent='Не удалось сохранить черновик';toast('Хранилище браузера недоступно или заполнено. Скачайте проект.');}}
async function restoreDraft(){try{db=await openDb();const result=await new Promise((resolve,reject)=>{const req=db.transaction('drafts').objectStore('drafts').get('latest');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(!result){await saveDraft();return;}const choice=await new Promise(resolve=>{modal('Продолжить редактирование?',`<p>Найден сохранённый черновик проекта. Выберите, что открыть.</p><div class="row"><button id="reset-draft" class="danger">Сбросить проект</button><button id="continue-draft" class="primary">Продолжить редактирование</button></div>`);$('#continue-draft').onclick=()=>{closeModal();resolve('continue');};$('#reset-draft').onclick=()=>{closeModal();resolve('reset');};});if(choice==='continue'){const restored=M.assertSchema(result.project);project=await optimizeLoaded(restored).catch(e=>{if(e.name==='AbortError')return restored;throw e;});savedSignature=result.savedSignature||'';heroId=project.heroes[0]?.id;taskId=hero()?.tasks[0]?.id;game.reset(project);render();$('#draft-state').textContent='✓ Черновик восстановлен в этом браузере';return;}await new Promise((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').delete('latest');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});project=M.demo();past.length=0;future.length=0;savedSignature='';heroId=project.heroes[0]?.id;taskId=hero()?.tasks[0]?.id;game.reset(project);render();await saveDraft();$('#draft-state').textContent='✓ Проект сброшен';}catch{$('#draft-state').textContent='Черновик недоступен — сохраняйте файл';}}
window.addEventListener('beforeunload',e=>{if(savedSignature!==signature(project)){e.preventDefault();e.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(saveTimer);saveDraft();}});
function sniff(bytes){if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)return 'image/png';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';const text=new TextDecoder().decode(bytes.slice(0,12));if(text.startsWith('GIF87a')||text.startsWith('GIF89a'))return 'image/gif';if(text.startsWith('RIFF')&&text.endsWith('WEBP'))return 'image/webp';if(text.startsWith('RIFF')&&text.endsWith('WAVE'))return 'audio/wav';if(text.startsWith('ID3')||(bytes[0]===255&&(bytes[1]&224)===224&&(bytes[1]&6)!==0))return 'audio/mpeg';throw Error('Фактический формат файла не поддерживается.');}
async function decodeAsset(blob,type){const url=URL.createObjectURL(blob);try{await new Promise((resolve,reject)=>{const el=type.startsWith('image/')?new Image():new Audio();const timer=setTimeout(()=>{el.src='';reject(Error('Не удалось декодировать ресурс.'));},15000);const finish=error=>{clearTimeout(timer);if(el instanceof HTMLAudioElement){el.pause();el.removeAttribute('src');el.load();}error?reject(Error('Повреждённый медиафайл.')):resolve();};if(el instanceof HTMLImageElement)el.onload=()=>finish();else el.onloadedmetadata=()=>finish();el.onerror=()=>finish(true);el.src=url;});}finally{URL.revokeObjectURL(url);}}
async function verifyAssets(p,cancelled=()=>false){for(const a of Object.values(p.assets)){if(cancelled())throw Error('Операция отменена');const bytes=PhoneArchive.fromData(a.data);if(sniff(bytes)!==a.type)throw Error('Формат ресурса не совпадает с манифестом.');await decodeAsset(new Blob([bytes],{type:a.type}),a.type);}}
async function optimizeLoaded(p){if(!Object.values(p.assets).some(a=>a.type.startsWith('image/')&&a.optimized!==PhoneMedia.VERSION))return p;const controller=new AbortController();modal('Сжимаем изображения проекта','<p id="media-progress">Подготавливаем картинки и GIF…</p><button id="cancel-media">Отменить</button>');working={cancel:()=>controller.abort()};$('#cancel-media').onclick=closeModal;const warnings=[];try{const result=await PhoneMedia.optimizeProject(p,{activeOnly:false,signal:controller.signal,onProgress:(n,total)=>{$('#media-progress').textContent=`Изображения и медиа: ${n} из ${total}`;},onWarning:name=>warnings.push(name)});if(warnings.length)toast('Некоторые файлы сохранены без дополнительного сжатия: '+warnings.length);return result;}finally{working=null;closeModal();}}
$('#media-file').onchange=async e=>{const file=e.target.files[0],target=mediaTarget;e.target.value='';if(!file||!target)return;let controller,mediaWarning='';try{if(file.size>20*1024*1024)throw Error('Файл больше 20 МБ. Выберите файл меньшего размера.');const bytes=new Uint8Array(await file.arrayBuffer()),type=sniff(bytes);if(type.startsWith('audio/')!==(target.kind==='audio'))throw Error('Неверный тип ресурса.');let blob=new Blob([bytes],{type});await decodeAsset(blob,type);let saved=file.size;if(type.startsWith('image/')){controller=new AbortController();modal('Сжимаем изображение',`<p>${E(file.name)}</p><p>Сохраняем пропорции и анимацию GIF.</p><div class="progress"><span></span></div><button id="cancel-media">Отменить</button>`);working={cancel:()=>controller.abort()};$('#cancel-media').onclick=closeModal;try{blob=await PhoneMedia.compress(blob,{...(PhoneMedia.profiles[target.kind]||PhoneMedia.profiles.image),signal:controller.signal});}catch(err){if(err.name==='AbortError')throw err;mediaWarning=' · сжатие не завершено, исходный файл сохранён';}saved=blob.size;if(controller.signal.aborted)throw Error('Операция отменена');working=null;closeModal();}if(target.heroId!==heroId||target.taskId!==taskId)throw Error('Выбранное задание изменилось. Повторите загрузку.');const data=PhoneArchive.toData(new Uint8Array(await blob.arrayBuffer()),blob.type);mutate(()=>{const id=M.uid();const duplicate=Object.entries(project.assets).find(([key,a])=>a.data===data);if(duplicate){setPath(target.path,duplicate[0]);return;}project.assets[id]={name:file.name,type:blob.type,data,...(type.startsWith('image/')&&!mediaWarning?{optimized:PhoneMedia.VERSION}:{})};setPath(target.path,id);});toast(type.startsWith('image/')?`Добавлено: ${size(file.size)} → ${size(saved)}${type==='image/gif'?' · анимация сохранена':''}${mediaWarning}`:'Аудио добавлено');}catch(e){working=null;if(controller)closeModal();toast(e.name==='AbortError'?'Загрузка отменена':e.message);}};
let embedRun=0;let embedSize={width:1200,height:675};
async function openGenially(optimize=false){const errors=M.validate(project);if(errors.length){showErrors(errors);return;}const run=++embedRun,source=M.exportCopy(project),controller=new AbortController();let current=source,payload='',descriptor=null;const warnings=[];modal(optimize?'Облегчить код для Genially':'Код для Genially',`<p>Вставьте весь код текущей игры в Genially через «Вставка → Другие / Внешнее содержимое».</p><div class="row"><label class="field"><span>Ширина слайда, px</span><input id="embed-width" type="number" min="280" max="7680" value="${embedSize.width}"></label><label class="field"><span>Высота слайда, px</span><input id="embed-height" type="number" min="200" max="4320" value="${embedSize.height}"></label></div><p class="hint">Растяните вставленный блок на весь слайд. Телефон автоматически впишется без боковой прокрутки.</p><details class="embed-hosted"><summary>Использовать адрес уже опубликованного HTML</summary><label class="field"><span>HTTPS-адрес игры (необязательно)</span><input id="embed-url" type="url" placeholder="https://.../game.html"></label></details><div class="embed-metrics" id="embed-metrics">Подготавливаем код…</div><textarea id="embed-code" readonly aria-label="Код для Genially" rows="5" placeholder="Подготовка игры…"></textarea><p id="embed-note" class="hint" role="status">Сжимаем изображения и собираем игру. Аудио сохраняется полностью.</p><div class="row"><button id="copy-embed" class="primary" disabled>Копировать код</button><button id="download-embed" disabled>Скачать код .txt</button><button id="lighten-embed" disabled>Облегчить код</button></div><div class="row embed-test-actions"><button id="test-embed" disabled>▷ Проверить игру</button><button id="open-embed" disabled>Открыть отдельно ↗</button></div><div class="row"><button id="embed-html">Скачать HTML</button><button id="embed-light-html">Облегчённый HTML</button></div><div id="embed-test"></div>`);working={cancel:()=>{controller.abort();embedRun++;}};
 const alive=()=>run===embedRun&&$('#dialog').open&&!controller.signal.aborted;
 const switchToHtml=compact=>{controller.abort();embedRun++;working=null;return exportHtml(compact,compact?current:source);};$('#embed-html').onclick=()=>switchToHtml(false);$('#embed-light-html').onclick=()=>switchToHtml(true);
 const options=()=>({width:embedSize.width,height:embedSize.height,title:source.name});
 const renderCode=()=>{if(!alive()||!payload)return;const w=+$('#embed-width').value,h=+$('#embed-height').value;let valid=Number.isInteger(w)&&w>=280&&w<=7680&&Number.isInteger(h)&&h>=200&&h<=4320;if(valid)embedSize={width:w,height:h};descriptor=PhoneEmbed.codeFor(payload,options());const custom=$('#embed-url').value.trim();if(custom){try{const url=new URL(custom);if(url.protocol!=='https:'||url.username||url.password)throw Error();descriptor={url:url.href,code:PhoneEmbed.iframe(url.href,w,h,source.name),extended:false};}catch{valid=false;}}$('#embed-code').value=valid?descriptor.code:'';for(const id of ['copy-embed','download-embed','test-embed','open-embed'])$('#'+id).disabled=!valid;$('#lighten-embed').disabled=optimize;const before=Object.values(source.assets).reduce((n,a)=>n+Math.floor((a.data.length-a.data.indexOf(',')-1)*.75),0),after=Object.values(current.assets).reduce((n,a)=>n+Math.floor((a.data.length-a.data.indexOf(',')-1)*.75),0);$('#embed-metrics').textContent=`${optimize?'Облегчённый код':'Сжатый код'}: ${size(new Blob([descriptor.code]).size)} · медиа ${size(before)} → ${size(after)}`;$('#embed-note').textContent=!valid?'Проверьте размеры слайда и HTTPS-адрес.':(descriptor.extended?'Большая игра: подготовлен расширенный HTML-код. Вставляйте его целиком. Для него платформа должна сохранять атрибут srcdoc.':'Код готов. После изменения игры сформируйте и вставьте новый код.')+(warnings.length?' '+warnings.length+' файлов сохранены без дополнительного сжатия; они включены в игру.':'');};
 try{current=await PhoneMedia.optimizeProject(source,{force:optimize,signal:controller.signal,onProgress:(n,total)=>{if(alive())$('#embed-metrics').textContent=`Обрабатываем медиа: ${n} из ${total}`;},onWarning:name=>warnings.push(name)});if(!alive())return;$('#embed-metrics').textContent='Сжимаем данные игры…';payload=await PhoneEmbed.encode(current,true);if(!alive())return;renderCode();$('#embed-width').oninput=renderCode;$('#embed-height').oninput=renderCode;$('#embed-url').oninput=renderCode;
 $('#copy-embed').onclick=async()=>{const field=$('#embed-code');const ok=await PhoneEmbed.copy(field.value,field);if(!alive())return;$('#embed-note').textContent=ok?'Код скопирован. Вставьте его в Genially.':'Код выделен — нажмите Ctrl/Cmd+C или скачайте код в файл.';toast(ok?'Код для Genially скопирован':'Скачайте код или скопируйте выделенный текст');};
 $('#download-embed').onclick=()=>{download(new Blob([$('#embed-code').value],{type:'text/plain;charset=utf-8'}),filename('.genially.txt'));toast('Код для Genially готов к скачиванию');};$('#lighten-embed').onclick=()=>openGenially(true);
 $('#test-embed').onclick=()=>{const iframe=document.createElement('iframe');iframe.title='Проверка игры для Genially';iframe.setAttribute('allow','autoplay; fullscreen');iframe.setAttribute('sandbox','allow-scripts allow-same-origin');iframe.style.cssText=`width:100%;height:auto;aspect-ratio:${embedSize.width}/${embedSize.height};border:1px solid #665276;border-radius:12px;background:#eee`;const preview=$('#embed-url').value.trim()?descriptor:PhoneEmbed.codeFor(payload,{...options(),base:['localhost','127.0.0.1'].includes(location.hostname)?new URL('player.html',location.href).href:PhoneEmbed.playerURL()});if(preview.document)iframe.srcdoc=preview.document;else iframe.src=preview.url;$('#embed-test').replaceChildren(iframe);iframe.scrollIntoView({block:'nearest',behavior:'smooth'});};
 $('#open-embed').onclick=()=>{if(descriptor.document){const url=URL.createObjectURL(new Blob([descriptor.document],{type:'text/html;charset=utf-8'}));window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000);}else window.open(descriptor.url,'_blank','noopener');};
 }catch(e){if(alive()){$('#embed-note').textContent=e.message;$('#embed-metrics').textContent='Не удалось подготовить код. HTML-экспорт остаётся доступен.';}}
}
$('#genially').onclick=()=>openGenially(false);
$('#optimize').onclick=()=>openGenially(true);
function size(n){return n>=1048576?(n/1048576).toFixed(2)+' МБ':(n/1024).toFixed(1)+' КБ';}
render();restoreDraft();
})();
