(function(root){'use strict';
const enc=new TextEncoder(),dec=new TextDecoder(),MAX_BYTES=160*1024*1024,MAX_URL=1500000;
const base64=bytes=>PhoneArchive.toData(bytes,'application/octet-stream').split(',')[1].replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
function bytes(text){if(!/^[A-Za-z0-9_-]+$/.test(text))throw Error('Повреждён код игры.');const value=text.replace(/-/g,'+').replace(/_/g,'/');return PhoneArchive.fromData('data:application/octet-stream;base64,'+value+'='.repeat((4-value.length%4)%4));}
async function transform(input,kind){const stream=new Blob([input]).stream().pipeThrough(kind==='gzip'?new CompressionStream('gzip'):new DecompressionStream('gzip')),reader=stream.getReader(),chunks=[];let size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>MAX_BYTES){await reader.cancel();throw Error('Игра превышает допустимый размер.');}chunks.push(r.value);}return new Uint8Array(await new Blob(chunks).arrayBuffer());}
async function encode(project,compact=true){const p=PhoneModel.exportCopy(project);const raw=enc.encode(JSON.stringify(p));if(raw.length>MAX_BYTES)throw Error('Игра превышает допустимый объём данных.');return (compact?'pg2z.':'pg2j.')+base64(compact?await transform(raw,'gzip'):raw);}
async function decode(hash){const value=hash.replace(/^#/,''),dot=value.indexOf('.'),prefix=value.slice(0,dot);if(!['pg2z','pg2j'].includes(prefix)||value.length>Math.ceil(MAX_BYTES*4/3)+1024)throw Error('Неверный или слишком длинный код игры.');let raw=bytes(value.slice(dot+1));if(prefix==='pg2z')raw=await transform(raw,'unzip');const p=PhoneModel.assertSchema(JSON.parse(dec.decode(raw)));const errors=PhoneModel.validate(p);if(errors.length)throw Error('В коде игры есть незаполненные задания.');return p;}
function playerURL(){if(/^https?:$/.test(location.protocol)&&!['localhost','127.0.0.1'].includes(location.hostname))return new URL('player.html',location.href).href;return 'https://galmizmaria-beep.github.io/telefon/player.html';}
function iframe(url,width,height,title){const e=PhoneGame.esc;return `<iframe src="${e(url)}" width="${width}" height="${height}" scrolling="no" style="display:block;width:100%;height:100%;border:0;overflow:hidden" title="${e(title)}" allow="autoplay; fullscreen" allowfullscreen></iframe>`;}
function documentFor(payload,base=playerURL()){const e=PhoneGame.esc,root=new URL('.',base).href;return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base href="${e(root)}"><link rel="stylesheet" href="src/game.css"><style>html,body{margin:0;width:100%;height:100%;overflow:hidden}.player-status{font:16px Arial;padding:20px}</style></head><body><main id="game"><div class="player-status">Загрузка игры…</div></main><script id="phonegame-data" type="application/json">${JSON.stringify(payload).replace(/</g,'\\u003c')}</script>${['vendor/katex/katex.min.js','src/model.js','src/i18n.js','src/math.js','src/game.js','src/archive.js','src/embed.js','src/player.js'].map(src=>`<script src="${src}"></script>`).join('')}</body></html>`;}
function codeFor(payload,{base=playerURL(),width=1200,height=675,title='Игра'}={}){const url=base+'#'+payload;if(url.length<=MAX_URL)return {code:iframe(url,width,height,title),url,document:null,extended:false};const doc=documentFor(payload,base);return {code:`<iframe src="${PhoneGame.esc(base)}" srcdoc="${PhoneGame.esc(doc)}" width="${width}" height="${height}" scrolling="no" style="display:block;width:100%;height:100%;border:0;overflow:hidden" title="${PhoneGame.esc(title)}" allow="autoplay; fullscreen" allowfullscreen></iframe>`,url:null,document:doc,extended:true};}
async function prepare(project,{compact=true,base=playerURL(),width=1200,height=675}={}){const payload=await encode(project,compact);return {payload,...codeFor(payload,{base,width,height,title:project.name}),tooLarge:false};}
// Synchronous fallback executes inside the original click gesture, including Safari/iframes.
async function copy(text,field){let legacy=false;const previous=document.activeElement;const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.cssText='position:fixed;left:0;top:0;opacity:.01;width:1px;height:1px';(field?.closest('dialog')||document.body).append(area);area.focus();area.select();area.setSelectionRange(0,area.value.length);try{legacy=document.execCommand('copy');}catch{}area.remove();previous?.focus({preventScroll:true});if(legacy)return true;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true;}}catch{}if(field){field.focus();field.select();field.setSelectionRange(0,field.value.length);}return false;}
root.PhoneEmbed={encode,decode,prepare,iframe,codeFor,documentFor,copy,playerURL,MAX_URL};
})(globalThis);
