(function(root){'use strict';
const enc=new TextEncoder(),dec=new TextDecoder(),MAX_BYTES=100*1024*1024,MAX_URL=1500000;
const base64=bytes=>PhoneArchive.toData(bytes,'application/octet-stream').split(',')[1].replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
function bytes(text){if(!/^[A-Za-z0-9_-]+$/.test(text))throw Error('Повреждён код игры.');const value=text.replace(/-/g,'+').replace(/_/g,'/');return PhoneArchive.fromData('data:application/octet-stream;base64,'+value+'='.repeat((4-value.length%4)%4));}
async function transform(input,kind){const stream=new Blob([input]).stream().pipeThrough(kind==='gzip'?new CompressionStream('gzip'):new DecompressionStream('gzip')),reader=stream.getReader(),chunks=[];let size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>MAX_BYTES){await reader.cancel();throw Error('Игра превышает допустимый размер.');}chunks.push(r.value);}return new Uint8Array(await new Blob(chunks).arrayBuffer());}
async function encode(project,compact=true){const p=PhoneModel.exportCopy(project);const raw=enc.encode(JSON.stringify(p));if(raw.length>MAX_BYTES)throw Error('Игра превышает 100 МБ.');return (compact?'pg2z.':'pg2j.')+base64(compact?await transform(raw,'gzip'):raw);}
async function decode(hash){const value=hash.replace(/^#/,''),dot=value.indexOf('.'),prefix=value.slice(0,dot);if(!['pg2z','pg2j'].includes(prefix)||value.length>MAX_URL)throw Error('Неверный или слишком длинный код игры.');let raw=bytes(value.slice(dot+1));if(prefix==='pg2z')raw=await transform(raw,'unzip');const p=PhoneModel.assertSchema(JSON.parse(dec.decode(raw)));const errors=PhoneModel.validate(p);if(errors.length)throw Error('В коде игры есть незаполненные задания.');return p;}
function playerURL(){if(/^https?:$/.test(location.protocol)&&!['localhost','127.0.0.1'].includes(location.hostname))return new URL('player.html',location.href).href;return 'https://galmizmaria-beep.github.io/telefon/player.html';}
function iframe(url,width,height,title){const e=PhoneGame.esc;return `<iframe src="${e(url)}" width="${width}" height="${height}" scrolling="no" style="display:block;width:100%;height:100%;border:0;overflow:hidden" title="${e(title)}" allow="autoplay; fullscreen" allowfullscreen></iframe>`;}
async function prepare(project,{compact=true,base=playerURL(),width=1200,height=675}={}){const payload=await encode(project,compact),url=base+'#'+payload;return {payload,url,code:iframe(url,width,height,project.name),tooLarge:url.length>MAX_URL};}
// Synchronous fallback executes inside the original click gesture, including Safari/iframes.
async function copy(text,field){let legacy=false;const previous=document.activeElement;const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.cssText='position:fixed;left:0;top:0;opacity:.01;width:1px;height:1px';(field?.closest('dialog')||document.body).append(area);area.focus();area.select();area.setSelectionRange(0,area.value.length);try{legacy=document.execCommand('copy');}catch{}area.remove();previous?.focus({preventScroll:true});if(legacy)return true;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true;}}catch{}if(field){field.focus();field.select();field.setSelectionRange(0,field.value.length);}return false;}
root.PhoneEmbed={encode,decode,prepare,iframe,copy,playerURL,MAX_URL};
})(globalThis);
