(function(root){
const keys=['play','contacts','submit','clear','next','correct','wrong','retry','win','complete','lose','again','calling','skip','hangup','close','keyboard','hide','space','backspace','shift','system','empty','score','of','finished','errors','lives','mute','unmute','ready','done','back','audioError','resetAnswer','up','down','replay','choose'];
const rows={
ru:['Играть','Контакты','Ответить','Очистить','Далее','Верно!','Неверно','Попробовать снова','Победа!','Игра завершена','Жизни закончились','Играть снова','Вызов…','Пропустить','Завершить звонок','Закрыть','Клавиатура','Скрыть','Пробел','Удалить','Регистр','Системный ввод','Введите или выберите ответ','Верно','из','Завершено','Ошибки','Жизни','Выключить звук','Включить звук','Готов к звонку','Выполнено','Назад','Звук недоступен. Можно продолжить игру.','Задание изменено. Тестовый ответ сброшен.','Вверх','Вниз','Повтор аудио','Выбрать'],
en:['Play','Contacts','Answer','Clear','Next','Correct!','Incorrect','Try again','You win!','Game completed','No lives left','Play again','Calling…','Skip','End call','Close','Keyboard','Hide','Space','Delete','Shift','System input','Enter or select an answer','Correct','of','Completed','Errors','Lives','Mute','Unmute','Ready to call','Done','Back','Audio unavailable. You can continue.','Task changed. Test answer reset.','Up','Down','Replay audio','Select'],
es:['Jugar','Contactos','Responder','Borrar','Siguiente','¡Correcto!','Incorrecto','Intentar de nuevo','¡Victoria!','Juego terminado','No quedan vidas','Volver a jugar','Llamando…','Omitir','Finalizar llamada','Cerrar','Teclado','Ocultar','Espacio','Borrar letra','Mayúsculas','Teclado del sistema','Escribe o selecciona una respuesta','Correctas','de','Completadas','Errores','Vidas','Silenciar','Activar sonido','Listo para llamar','Completado','Atrás','Audio no disponible. Puedes continuar.','Actividad modificada. Respuesta de prueba borrada.','Arriba','Abajo','Repetir audio','Seleccionar'],
fr:['Jouer','Contacts','Répondre','Effacer','Suivant','Correct !','Incorrect','Réessayer','Victoire !','Jeu terminé','Plus de vies','Rejouer','Appel…','Passer','Raccrocher','Fermer','Clavier','Masquer','Espace','Supprimer','Majuscules','Clavier système','Saisissez ou choisissez une réponse','Correctes','sur','Terminées','Erreurs','Vies','Couper le son','Activer le son','Prêt à appeler','Terminé','Retour','Son indisponible. Vous pouvez continuer.','Exercice modifié. Réponse de test effacée.','Monter','Descendre','Réécouter','Choisir'],
de:['Spielen','Kontakte','Antworten','Löschen','Weiter','Richtig!','Falsch','Erneut versuchen','Gewonnen!','Spiel beendet','Keine Leben mehr','Erneut spielen','Anruf…','Überspringen','Auflegen','Schließen','Tastatur','Ausblenden','Leerzeichen','Entfernen','Umschalten','Systemtastatur','Antwort eingeben oder auswählen','Richtig','von','Abgeschlossen','Fehler','Leben','Ton aus','Ton an','Bereit zum Anruf','Erledigt','Zurück','Ton nicht verfügbar. Du kannst weiterspielen.','Aufgabe geändert. Testantwort gelöscht.','Nach oben','Nach unten','Audio wiederholen','Auswählen'],
tr:['Oyna','Kişiler','Yanıtla','Temizle','İleri','Doğru!','Yanlış','Tekrar dene','Kazandın!','Oyun tamamlandı','Can kalmadı','Yeniden oyna','Aranıyor…','Atla','Aramayı bitir','Kapat','Klavye','Gizle','Boşluk','Sil','Büyük harf','Sistem klavyesi','Bir yanıt yazın veya seçin','Doğru','/','Tamamlanan','Hatalar','Canlar','Sesi kapat','Sesi aç','Aramaya hazır','Tamamlandı','Geri','Ses kullanılamıyor. Devam edebilirsiniz.','Görev değişti. Deneme yanıtı sıfırlandı.','Yukarı','Aşağı','Sesi tekrar oynat','Seç'],
kk:['Ойнау','Байланыстар','Жауап беру','Тазалау','Келесі','Дұрыс!','Қате','Қайталап көру','Жеңіс!','Ойын аяқталды','Өмір қалмады','Қайта ойнау','Қоңырау шалынуда…','Өткізіп жіберу','Қоңырауды аяқтау','Жабу','Пернетақта','Жасыру','Бос орын','Өшіру','Бас әріп','Жүйелік пернетақта','Жауапты енгізіңіз немесе таңдаңыз','Дұрыс','/','Аяқталған','Қателер','Өмірлер','Дыбысты өшіру','Дыбысты қосу','Қоңырауға дайын','Орындалды','Артқа','Дыбыс қолжетімсіз. Ойынды жалғастыра аласыз.','Тапсырма өзгерді. Сынақ жауабы тазартылды.','Жоғары','Төмен','Аудионы қайталау','Таңдау'],
it:['Gioca','Contatti','Rispondi','Cancella','Avanti','Corretto!','Errato','Riprova','Vittoria!','Gioco completato','Vite esaurite','Gioca ancora','Chiamata…','Salta','Termina chiamata','Chiudi','Tastiera','Nascondi','Spazio','Elimina','Maiuscole','Tastiera di sistema','Inserisci o scegli una risposta','Corrette','su','Completate','Errori','Vite','Disattiva audio','Attiva audio','Pronto a chiamare','Completato','Indietro','Audio non disponibile. Puoi continuare.','Attività modificata. Risposta di prova cancellata.','Su','Giù','Ripeti audio','Seleziona'],
pt:['Jogar','Contatos','Responder','Limpar','Próximo','Correto!','Incorreto','Tentar novamente','Vitória!','Jogo concluído','Sem vidas','Jogar novamente','Chamando…','Pular','Encerrar chamada','Fechar','Teclado','Ocultar','Espaço','Apagar','Maiúsculas','Teclado do sistema','Digite ou selecione uma resposta','Corretas','de','Concluídas','Erros','Vidas','Silenciar','Ativar som','Pronto para chamar','Concluído','Voltar','Áudio indisponível. Você pode continuar.','Atividade alterada. Resposta de teste apagada.','Subir','Descer','Repetir áudio','Selecionar']};
root.PhoneI18n={keys,rows,t:(p,key)=>p.language.overrides[key]||rows[p.language.locale]?.[keys.indexOf(key)]||rows.en[keys.indexOf(key)]||key};
})(globalThis);
