(function(root){'use strict';
const VERSION=2;
const profiles={avatar:{max:256,targetBytes:24*1024},image:{max:720,targetBytes:80*1024},background:{max:1200,targetBytes:150*1024}};
function compress(blob,{max=720,targetBytes=80*1024,signal}={}){return new Promise(async(resolve,reject)=>{if(signal?.aborted)return reject(new DOMException('Операция отменена','AbortError'));let worker,timer,settled=false;const finish=(err,value)=>{if(settled)return;settled=true;clearTimeout(timer);worker?.terminate();signal?.removeEventListener('abort',abort);err?reject(err):resolve(value);};const abort=()=>finish(new DOMException('Операция отменена','AbortError'));signal?.addEventListener('abort',abort,{once:true});try{const buffer=await blob.arrayBuffer();if(signal?.aborted)return abort();worker=new Worker(new URL('media-worker.js',document.currentScript?.src||new URL('src/media.js',location.href)),{type:'module'});worker.onmessage=({data})=>data.error?finish(Error(data.error)):finish(null,new Blob([data.buffer],{type:data.type}));worker.onerror=()=>finish(Error('Не удалось сжать изображение. Откройте редактор по HTTPS или localhost.'));timer=setTimeout(()=>finish(Error('Обработка изображения заняла слишком много времени.')),90000);worker.postMessage({buffer,type:blob.type,max,targetBytes},[buffer]);}catch(e){finish(e);}});}
function profileFor(project,id){let kind='avatar';if(project.design.background===id||project.design.screenBackground===id)kind='background';else if(['win','complete','lose'].some(k=>project.screens[k+'Image']===id)||project.heroes.some(h=>h.tasks.some(t=>t.image===id)))kind='image';return profiles[kind];}
function remapAssets(p,remap){const ref=id=>remap[id]||id;p.design.background=ref(p.design.background);p.design.screenBackground=ref(p.design.screenBackground);for(const k of ['win','complete','lose'])p.screens[k+'Image']=ref(p.screens[k+'Image']);for(const k of ['ring','correct','wrong'])p.sounds[k+'Asset']=ref(p.sounds[k+'Asset']);p.heroes.forEach(h=>{h.avatar=ref(h.avatar);h.tasks.forEach(t=>{t.image=ref(t.image);t.audio=ref(t.audio);});});}
async function optimizeProject(project,{signal,onProgress=()=>{},onWarning=()=>{},activeOnly=true,force=false}={}){const p=activeOnly?PhoneModel.exportCopy(project):PhoneModel.clone(project),entries=Object.entries(p.assets),seen=new Map(),remap={};
// Deduplicate before expensive work, using the largest display role among references.
for(const [id,a] of entries){if(seen.has(a.data)){remap[id]=seen.get(a.data);delete p.assets[id];}else seen.set(a.data,id);}remapAssets(p,remap);
const unique=Object.entries(p.assets);for(let i=0;i<unique.length;i++){if(signal?.aborted)throw new DOMException('Операция отменена','AbortError');const [id,a]=unique[i];onProgress(i+1,unique.length);if(!a.type.startsWith('image/'))continue;const baseProfile=profileFor(p,id),profile=force?{max:Math.round(baseProfile.max*.8),targetBytes:Math.round(baseProfile.targetBytes*.6)}:baseProfile,bytes=!force&&a.optimized===VERSION?null:PhoneArchive.fromData(a.data);if(!bytes)continue;
try{const source=new Blob([bytes],{type:a.type}),out=await compress(source,{...profile,signal});if(out.size<source.size){a.data=PhoneArchive.toData(new Uint8Array(await out.arrayBuffer()),out.type);a.type=out.type;}a.optimized=VERSION;}catch(e){if(e.name==='AbortError')throw e;onWarning(a.name,e.message);}}
return p;}
root.PhoneMedia={compress,optimizeProject,profiles,VERSION};
})(globalThis);
